/**
 * Icônes pixel-art originales, dessinées à la main sur une grille 12×12.
 * Chaque caractère est un pixel ; « . » = transparent ; « c » = couleur courante (currentColor).
 * Rendu en SVG par <PixelIcon> (un <path> par couleur, rendu net « crispEdges »).
 */

export const PIXEL_PALETTE: Record<string, string> = {
  k: '#3b2616', // contour encre
  d: '#7a4a26', // bois sombre
  w: '#a8703c', // bois
  W: '#e2b67c', // bois clair
  l: '#fffcf4', // blanc crème
  p: '#f7e8c6', // papier
  P: '#d9b880', // papier ombré
  r: '#d8433b', // rouge
  R: '#9c2a2a', // rouge sombre
  g: '#5aa845', // vert
  G: '#357029', // vert sombre
  y: '#ffd54a', // jaune
  Y: '#d99412', // or sombre
  b: '#79c5ee', // bleu
  B: '#2f78b8', // bleu sombre
  o: '#ee8030', // orange
  n: '#f7b8cc', // rose
  N: '#d94f84', // rose sombre
  v: '#9a66d0', // violet
  x: '#b4b4c0', // gris
  X: '#6a6a7a', // gris sombre
  c: 'currentColor',
}

export const PIXEL_ICONS = {
  farm: [
    '....kkkk....',
    '...krrrrk...',
    '..krrllrrk..',
    '.krrrllrrrk.',
    'krrrrrrrrrrk',
    'kkRRRRRRRRkk',
    '.krllllllrk.',
    '.krlRkkRlrk.',
    '.krlkRRklrk.',
    '.krlkRRklrk.',
    '.krlRkkRlrk.',
    '.kkkkkkkkkk.',
  ],
  objectives: [
    '.....kk.....',
    '....krrk....',
    '.kkkkRRkkkk.',
    '.kpppkkpppk.',
    '.kpddddddpk.',
    '.kppppppppk.',
    '.kpddddpppk.',
    '.kppppppppk.',
    '.kpddddddpk.',
    '.kppppppPPk.',
    '.kPPPPPPPPk.',
    '.kkkkkkkkkk.',
  ],
  sprite: [
    '......k.....',
    '.....kck....',
    '.....kcck...',
    '....kccck...',
    '...kccccck..',
    '..kkkkkkkk..',
    '..kllllllk..',
    '.kllkllkllk.',
    '.klnllllnlk.',
    '.kllllllllk.',
    '..kllllllk..',
    '...kkkkkk...',
  ],
  calendar: [
    '..kk....kk..',
    '.kkkkkkkkkk.',
    '.krrrrrrrrk.',
    '.krrrrrrrrk.',
    '.kkkkkkkkkk.',
    '.kpPppPppPk.',
    '.kppppppppk.',
    '.kpPppPpNNk.',
    '.kpppppNNNk.',
    '.kpPppPppPk.',
    '.kppppppppk.',
    '.kkkkkkkkkk.',
  ],
  notebook: [
    '.kkkkkkkkkk.',
    '.kdwwwwwwwk.',
    '.kdwppppwwk.',
    '.kdwpddpwwk.',
    '.kdwppppwwk.',
    '.kdwwwwwwwk.',
    '.kdwwwwwwwk.',
    '.kdwwwwwwwk.',
    '.kdkkkkkkkk.',
    '.kdllllllrk.',
    '.kkkkkkkkrk.',
    '........rr..',
  ],
  recipe: [
    '....x..x....',
    '...x..x.....',
    '....x..x....',
    '..kkkkkkkk..',
    '.kRRRRRRRRk.',
    'kkkkkkkkkkkk',
    'kRkrrrrrrkRk',
    '.krrrllrrrk.',
    '.krrrrrrrrk.',
    '.kRrrrrrrRk.',
    '..kRRRRRRk..',
    '...kkkkkk...',
  ],
  account: [
    '....kkkk....',
    '...kyyyyk...',
    '.kkkYYYYkkk.',
    'kyyyyyyyyyyk',
    '.kkkkkkkkkk.',
    '..kWWWWWWk..',
    '..kWkWWkWk..',
    '..kWWnnWWk..',
    '...kkWWkk...',
    '..kbbbbbbk..',
    '.kbbBbbBbbk.',
    '.kkkkkkkkkk.',
  ],
  settings: [
    '....kkkk....',
    '.kk.kxxk.kk.',
    '.kxkkxxkkxk.',
    '..kxxxxxxk..',
    'kkkxxkkxxkkk',
    'kxxxk..kxxxk',
    'kxxxk..kxxxk',
    'kkkxxkkxxkkk',
    '..kxxxxxxk..',
    '.kxkkxxkkxk.',
    '.kk.kxxk.kk.',
    '....kkkk....',
  ],
  pencil: [
    '............',
    '........kkk.',
    '.......knnnk',
    '......kxnnk.',
    '.....kyxxk..',
    '....kyyyk...',
    '...kyyyk....',
    '..kyyyk.....',
    '.kWyyk......',
    '.kWWk.......',
    '.kkk........',
    '............',
  ],
  check: [
    '............',
    '.........kk.',
    '........kggk',
    '.......kggk.',
    '.kk...kggk..',
    'kggk.kggk...',
    '.kggkggk....',
    '..kgggk.....',
    '...kgk......',
    '....k.......',
    '............',
    '............',
  ],
  lock: [
    '....kkkk....',
    '...kxxxxk...',
    '..kxk..kxk..',
    '..kxk..kxk..',
    '..kxk..kxk..',
    '.kkkkkkkkkk.',
    '.kyyyyyyyyk.',
    '.kyyykkyyyk.',
    '.kYyykkyyYk.',
    '.kYyyyyyyYk.',
    '.kYYYYYYYYk.',
    '.kkkkkkkkkk.',
  ],
  pin: [
    '....kkkk....',
    '...krrlrk...',
    '..krrrlrrk..',
    '..krrrrrrk..',
    '..kRrrrrRk..',
    '...kRRRRk...',
    '....kkkk....',
    '.....kk.....',
    '.....xk.....',
    '.....xk.....',
    '......k.....',
    '............',
  ],
  star: [
    '.....kk.....',
    '....kyyk....',
    '....kyyk....',
    'kkkkkyykkkkk',
    'kyyyyyyyyyYk',
    '.kyyyyyyyYk.',
    '..kyyyyyYk..',
    '..kyyyyyYk..',
    '.kyyYkkYyYk.',
    '.kyYk..kYYk.',
    'kYYk....kYYk',
    'kkk......kkk',
  ],
  search: [
    '..kkkkk.....',
    '.kbbbbbk....',
    'kbllbbbbk...',
    'kblbbbbbk...',
    'kbbbbbbbk...',
    'kbbbbbbBk...',
    '.kbbbbBk....',
    '..kkkkkdk...',
    '.......kdk..',
    '........kdk.',
    '.........kdk',
    '..........k.',
  ],
  heart: [
    '............',
    '.kkk...kkk..',
    'krrrk.krrrk.',
    'krlrrkrrrrk.',
    'krrrrrrrrrk.',
    'krrrrrrrrRk.',
    '.krrrrrrRk..',
    '..krrrrRk...',
    '...krrRk....',
    '....kRk.....',
    '.....k......',
    '............',
  ],
  coin: [
    '...kkkkkk...',
    '..kyyyyyyk..',
    '.kyylyyyyYk.',
    'kyylkkkkyyYk',
    'kyylkyyyyyYk',
    'kyyykkkkyyYk',
    'kyyyyyykyyYk',
    'kyyykkkkyyYk',
    'kyyyyyyyyyYk',
    '.kyyyyyyyYk.',
    '..kYYYYYYk..',
    '...kkkkkk...',
  ],
  flag: [
    '.kk.........',
    '.kdkkkkkk...',
    '.kdkrrrrrk..',
    '.kdkrlrrrrk.',
    '.kdkrrrrrrk.',
    '.kdkRrrrrk..',
    '.kdkkkkkk...',
    '.kdk........',
    '.kdk........',
    '.kdk........',
    'kkdkk.......',
    'kkkkk.......',
  ],
  cake: [
    '.....k......',
    '....kyk.....',
    '.....k......',
    '.....r......',
    '..kkkkkkkk..',
    '.knnnnnnnnk.',
    '.klnlnlnlnk.',
    '.kWWWWWWWWk.',
    '.kNNNNNNNNk.',
    '.kWWWWWWWWk.',
    'kkkkkkkkkkkk',
    '.kkkkkkkkkk.',
  ],
  pickaxe: [
    '..kkkkkk....',
    '.kxxxxxxkk..',
    'kxkkkkkxxk..',
    'kk...kdkxxk.',
    '....kdk.kxk.',
    '...kdk...kxk',
    '..kdk.....kk',
    '.kdk........',
    'kdk.........',
    'kk..........',
    '............',
    '............',
  ],
  hammer: [
    '...kkkkk....',
    '..kxxxxxk...',
    '.kxxxxxxxk..',
    '.kXxxxxxxxk.',
    '..kkkkdkkk..',
    '.....kdk....',
    '.....kdk....',
    '.....kdk....',
    '.....kdk....',
    '.....kdk....',
    '.....kdk....',
    '.....kkk....',
  ],
  chicken: [
    '...kk.......',
    '..krrk......',
    '..kllk......',
    '.kllkl......',
    'kyklllk.....',
    '.kklllkkkk..',
    '..klllllllk.',
    '..kllxlllxlk',
    '..klllllllk.',
    '...kllllllk.',
    '....kkkkkk..',
    '.....y..y...',
  ],
  turnip: [
    '...g...g....',
    '..gGg.gGg...',
    '...gGgGg....',
    '....kGk.....',
    '..kknnkk....',
    '.knlnnnnk...',
    'knlllllllk..',
    'kllllllllk..',
    'klllllllxk..',
    '.klllllxk...',
    '..kkllkk....',
    '....kk......',
  ],
  moneybag: [
    '...kkkkk....',
    '....kWk.....',
    '...kdddk....',
    '..kWWWWWk...',
    '.kWWWkWWWk..',
    'kWWWkkkWWWk.',
    'kWWWkWWWWWk.',
    'kWWWkkkWWWk.',
    'kWWWWWkWWWk.',
    'kWWWkkkWWdk.',
    '.kWWWWWWdk..',
    '..kkkkkkk...',
  ],
  goddess: [
    '.....y......',
    '.....y......',
    '..y.kkk.y...',
    '...knnnk....',
    'yykkknkkkyy.',
    '.knnkykknnk.',
    '.knnkykknnk.',
    '..kkknkkk...',
    '...knnnk....',
    '..y.kkk.y...',
    '.....y......',
    '.....y......',
  ],
  ring: [
    '....kkk.....',
    '...kbllk....',
    '....kbk.....',
    '...kkkkk....',
    '..kyyyyyk...',
    '.kyykkkyyk..',
    '.kyk...kyk..',
    '.kyk...kYk..',
    '.kyk...kYk..',
    '.kyYkkkYYk..',
    '..kYYYYYk...',
    '...kkkkk....',
  ],
  house: [
    '.....kk.....',
    '....kRRk.kk.',
    '...kRRRRkdk.',
    '..kRRRRRRkk.',
    '.kRRRRRRRRk.',
    'kkkkkkkkkkkk',
    '.kWWWWWWWWk.',
    '.kWbbWWkkWk.',
    '.kWbbWkddkk.',
    '.kWWWWkddWk.',
    '.kWWWWkddWk.',
    'kkkkkkkkkkkk',
  ],
  cow: [
    '.kk......kk.',
    '.kWk....kWk.',
    '..kkkkkkkk..',
    '.klkkllllkk.',
    '.kkklllkllk.',
    '.klklllklkk.',
    '.kllllllllk.',
    '..knnnnnnk..',
    '..knknnknk..',
    '..knnnnnnk..',
    '...kkkkkk...',
    '............',
  ],
  sparkle: [
    '.....k......',
    '....kyk.....',
    '....kyk.....',
    '...kyyyk....',
    'kkkyyyyykkk.',
    '.kyyylyyyk..',
    'kkkyyyyykkk.',
    '...kyyyk....',
    '....kyk...k.',
    '....kyk..kyk',
    '.....k....k.',
    '............',
  ],
  door: [
    '.kkkkkkkk...',
    '.kddddddk...',
    '.kdwwwwdk...',
    '.kdwwwwdk.k.',
    '.kdwwwwdkkyk',
    '.kdwwywdkyyk',
    '.kdwwwwdkkyk',
    '.kdwwwwdk.k.',
    '.kdwwwwdk...',
    '.kdwwwwdk...',
    '.kddddddk...',
    'kkkkkkkkkk..',
  ],
  back: [
    '............',
    '....kk......',
    '...kWk......',
    '..kWWkkkkkk.',
    '.kWWWWWWWWk.',
    'kWWWWWWWWWk.',
    '.kWWWWWWWWk.',
    '..kWWkkkkkk.',
    '...kWk......',
    '....kk......',
    '............',
    '............',
  ],
  close: [
    '............',
    '.kk......kk.',
    'krrk....krrk',
    '.krrk..krrk.',
    '..krrkkrrk..',
    '...krrrrk...',
    '...krrrrk...',
    '..krrkkrrk..',
    '.krrk..krrk.',
    'krrk....krrk',
    '.kk......kk.',
    '............',
  ],
  book: [
    '............',
    '.kkkkk.kkkk.',
    'kpppppkppppk',
    'kpdddpkpddpk',
    'kpppppkppppk',
    'kpdddpkpddpk',
    'kpppppkppppk',
    'kpdddpkpddpk',
    'kpppppkppppk',
    'kkkkkkkkkkkk',
    '.....kk.....',
    '............',
  ],
  leaf: [
    '.........kk.',
    '......kkkgk.',
    '....kkggggk.',
    '...kgggggGk.',
    '..kggggggGk.',
    '..kgggggGGk.',
    '.kgggggGGk..',
    '.kgggGGGk...',
    '.kgGGGkk....',
    '.kGkkk......',
    'kk..........',
    '............',
  ],
  sound: [
    '............',
    '.....kk.....',
    '....kxk..k..',
    '.kkkxxk...k.',
    '.kxxxxk.k.k.',
    '.kxxxxk.k.k.',
    '.kxxxxk.k.k.',
    '.kkkxxk...k.',
    '....kxk..k..',
    '.....kk.....',
    '............',
    '............',
  ],
} as const satisfies Record<string, readonly string[]>

export type PixelIconName = keyof typeof PIXEL_ICONS

export interface PixelLayer {
  color: string
  d: string
}

/** Convertit une grille en un <path> par couleur (rectangles 1×1 fusionnés horizontalement). */
export function gridToLayers(
  grid: readonly string[],
  palette: Record<string, string> = PIXEL_PALETTE,
): PixelLayer[] {
  const paths = new Map<string, string[]>()
  grid.forEach((row, y) => {
    let x = 0
    while (x < row.length) {
      const char = row[x]!
      if (char === '.' || !(char in palette)) {
        x++
        continue
      }
      let run = 1
      while (row[x + run] === char) run++
      const color = palette[char]!
      const list = paths.get(color) ?? []
      list.push(`M${x} ${y}h${run}v1h-${run}z`)
      paths.set(color, list)
      x += run
    }
  })
  return [...paths.entries()].map(([color, parts]) => ({ color, d: parts.join('') }))
}
